### ISSUE TITLE
Scrapy_Splash Issue --nested lua script function

### ISSUE THREAD

**Issue by shrutiwali-gep** [verzola/scrapy-splash-example#1]
i am completely new to python and Scrapy. As i am working on crawling the website for automation.
i can able to login but how can i get the redirected URL and how to create another Lua script for the new URL to perform the further operations on the web page. 

# -*- coding: utf-8 -*-
import json

from six.moves.urllib.parse import urljoin

import scrapy
import splash
from scrapy.utils.response import open_in_browser
from scrapy_splash import SplashRequest

class GitHubSpider(scrapy.Spider):

    name = 'githubspider'
    start_urls = [
        'https://smartuat.gep.com/',
    ]
    render_wait_time = 10.5
    time_out = 500

    def start_requests(self):
        nextpage_lua = """
           function main(splash)
            local url = splash.args.url
            assert(splash:go(url))
            assert(splash:wait(1))

            splash:set_viewport_full()

            local user_input = splash:select('input#UserName')
            user_input:send_text("Tester6")
            local pass_input = splash:select('input#Password')
            pass_input:send_text("Password@12345")
            assert(splash:wait(5))

            local submit_button = splash:select('input#login')
            submit_button:click()

              assert(splash:wait(15))
              move_to_dashboard(splash)
            -- return result as a JSON object
            return {
                url = splash:url(),  
                cookies = splash:get_cookies(),
                url = splash:url(),
                html = splash:html(),
                -- we don't need screenshot or network activity
                --png = splash:png(),
                --har = splash:har(),
            }
        end
        
        function move_to_dashboard(splash)
           local url = splash.url()
            assert(splash:go(url))
            assert(splash:wait(1))

            splash:set_viewport_full()                                       
            local submit_button = splash:select('i.icon.icon-fix-overlay.iconSmall')
            submit_button:click()
            assert(splash:wait(5))
            local submit_button = splash:select('div:contains("Project Request")')
            submit_button:click()
         return {
           url = splash:url(),
           html = splash:html(),
         }
       end
       
        """
        try:
            for url in self.start_urls:
                print('Start crawling with: ' + url)
                yield scrapy.Request(url, self.parse, dont_filter=False, meta={
                    'splash': {

                        'args': {'lua_source': nextpage_lua},
                        'endpoint': 'execute',
                    }
                })

        except Exception as abc:
            print("exception occured here in loop")

    def parse(self, response):
        print("parse: " + response.url)
        baseurl = response.meta["splash"]["args"]["url"]
        print("parseBase: " + baseurl)
        splash_json = json.loads(response.body_as_unicode())
        try:
            selector = scrapy.Selector(text=splash_json["html"], type="html")
            print(selector.xpath('//title/text()').extract())
        except Exception as inst:
            print("exception occured here")

**Comment by verzola** [comment]
Hey! This is just a example repository of using Scrapy with Splash.
If you have an issue with these technologies, I suggest you open an issue in the respective repositories:
https://github.com/scrapy/scrapy
https://github.com/scrapinghub/splash
https://github.com/scrapy-plugins/scrapy-splash
